#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1'
bspc rule -a code-oss desktop='^2'
bspc rule -a thunar desktop='^3'
sbpc rule -a xfce4-terminal -o desktop='^4'
bspc rule -a spotify -o desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Border
bspc config focused_border_color        "#333"
bspc config normal_border_color         "#111"
bspc config active_border_color         "#555"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh --shapes
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &